"""Initial revision111

Revision ID: 070d003d4342
Revises: ea41a57311ed
Create Date: 2025-01-01 05:25:14.516149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070d003d4342'
down_revision: Union[str, None] = 'ea41a57311ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('category_name', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'images', 'categories', ['category_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'category_name')
    # ### end Alembic commands ###
