"""Добавление image_count функции

Revision ID: 5d8659eb5e0e
Revises: 070d003d4342
Create Date: 2025-01-02 09:27:40.290113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8659eb5e0e'
down_revision: Union[str, None] = '070d003d4342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_count', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'images', ['image_count'])
    op.drop_constraint('images_category_name_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('category_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('images_category_name_fkey', 'images', 'categories', ['category_name'], ['name'], ondelete='CASCADE')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'image_count')
    # ### end Alembic commands ###
