"""Исправление

Revision ID: 99a8fbbca7c4
Revises: 5d8659eb5e0e
Create Date: 2025-01-02 09:38:46.265863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a8fbbca7c4'
down_revision: Union[str, None] = '5d8659eb5e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_image_count_key', 'images', type_='unique')
    op.drop_column('images', 'image_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('images_image_count_key', 'images', ['image_count'])
    # ### end Alembic commands ###
